<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @see \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<nav class="navigation" role="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?php $url = $block->getUrl();
             //$base = $this->_storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
        ?>
        <!--<li class="level0 <?php //if ($url== $base) {echo 'active';}?>">
            <a href="<?php //echo $base; ?>" class="level-top"><span><?php //echo $this->__('Home') ?></span></a>
        </li>-->
        <li class="level0">Home</li>
        <?php /* @escapeNotVerified */ echo $_menu; ?>
    </ul>

</nav>
