<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @see \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<?php $url = \Magento\Framework\App\ObjectManager::getInstance()
    ->get('Magento\Framework\UrlInterface');
?>

<nav class="navigation" role="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?php //$url = Mage::helper('core/url')->getCurrentUrl();
             $base = $this->getUrl();
        ?>
        <li class="level0  <?php //if ($url== $base) {echo 'active';}?>"><a href="<?php echo $base; ?>" class="level-top">
                <span class="icon i-home-w"></span>
                <span>Home</span></a></li>
        <?php /* @escapeNotVerified */ echo $_menu; ?>
    </ul>

</nav>
