<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<small class="copyright">
    <span><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></span>
</small>
<a href="#top" id="scroll-to-top">To top</a>

<script type="text/javascript">
    //<![CDATA[

    require(["jquery"],function($){
        var windowScroll_t;

        $(window).scroll(function(){

            clearTimeout(windowScroll_t);
            windowScroll_t = setTimeout(function() {

                if ($(this).scrollTop() > 100)
                {
                    $('#scroll-to-top').fadeIn();
                }
                else
                {
                    $('#scroll-to-top').fadeOut();
                }

            }, 500);

        });

        $('#scroll-to-top').click(function(){
            $("html, body").animate({scrollTop: 0}, 600, "easeOutCubic");
            return false;
        });


    });


    //]]>
</script>