<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @see \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<?php $url = \Magento\Framework\App\ObjectManager::getInstance()
    ->get('Magento\Framework\UrlInterface')->getCurrentUrl();
?>

<nav class="navigation" role="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?php //$url = Mage::helper('core/url')->getCurrentUrl();
             $base = $this->getUrl();
        ?>
        <div class="<?php echo $url?>"></div>
        <li class="level0  <?php if ($url== $base) {echo 'active';}?>"><a href="<?php echo $base; ?>" class="level-top feature-icon-hover">
                <span class="icon i-home-bw"></span>
                <span>Home</span></a>
        </li>

        <!--Shop all Products menu -->
        <?php /* @escapeNotVerified */ echo $_menu; ?>

        <!--Shop By Brands menu -->
        <?php $brandUrl = $base . "brand";?>
        <li class="level0 nav-2 brand level-top parent ui-menu-item <?php if (strpos($url, $brandUrl, 0)===0) {echo 'active';}?>" role="presentation">
           <?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
              $category = $objectManager->create('Magento\Catalog\Model\Category');
              $category->load(29);
            ?>
            <a id="ui-id-5" class="level-top ui-corner-all" href="#" aria-haspopup="true" tabindex="-1" role="menuitem">
                <span class="ui-menu-icon ui-icon ui-icon-carat-1-e"></span>
                <span><?php echo $category->getName();  ?></span>
            </a>
            <ul class="level0 submenu ui-menu ui-widget ui-widget-content ui-corner-all" style="display: none; top: 46.8px; left: -0.316667px;" role="menu" aria-expanded="false" aria-hidden="true">
            <?php
            $categoryBrandsIds = $category->getChildren();
            $iterator=0;
            $first=" first";
            $last = " last";
            foreach(explode(',',$categoryBrandsIds) as $categoryBrandId)
            {
                $categoryBrand = $objectManager->create('Magento\Catalog\Model\Category')->load($categoryBrandId);
                $categoryBrandName = $categoryBrand->getName();

                $VesBrands = $objectManager->create('Ves\Brand\Model\ResourceModel\Brand\Collection')
                    ->addFieldToFilter('name', $categoryBrandName);

                foreach($VesBrands as $Ves)
                { $iterator++;
                    ?>

                    <li class="level1 nav-2-<?php echo $iterator; ?><?php if($iterator==1) {echo $first;}else if($iterator==16){echo $last;} ?> ui-menu-item" role="presentation">
                        <a id="ui-id-44" class="ui-corner-all" href="<?php echo $Ves->getUrl(); ?>" tabindex="-1" role="menuitem">
                            <img src="<?php echo $Ves->getThumbnailUrl(); ?>" alt="<?php echo $Ves->getName() ?>"><span><?php echo $Ves->getName() ?> </span>
                        </a>
                    </li>

               <?php }
            }
            ?>
                </ul>
        </li>

        <!--Who we are menu -->
        <?php
        $aboutCategory = $objectManager->create('Magento\Catalog\Model\Category');
        $aboutCategory->load(26);
        ?>

        <li class="level0 nav-3 level-top ui-menu-item <?php if ($url === $aboutCategory->getUrl()) {echo 'active';}?>" role="presentation">
            <a id="ui-id-6" class="level-top ui-corner-all" href="<?php echo $aboutCategory->getUrl(); ?>" tabindex="-1" role="menuitem">
              <span><?php echo $aboutCategory->getName(); ?></span>
            </a>
       </li>

        <!--Blog menu -->
          <?php
          $blogCategory = $objectManager->create('Magento\Catalog\Model\Category');
          $blogCategory->load(88);
         ?>
        <li class="level0 nav-4 level-top ui-menu-item <?php if ($url === $blogCategory->getUrl()) {echo 'active';}?>" role="presentation">
            <a id="ui-id-7" class="level-top ui-corner-all" href="<?php echo $blogCategory->getUrl();?>" tabindex="-1" role="menuitem">
                <span><?php echo $blogCategory->getName();  ?></span>
            </a>
        </li>

        <!--Contact us menu -->
        <?php
        $contactCategory = $objectManager->create('Magento\Catalog\Model\Category');
        $contactCategory->load(89); ?>

        <li class="level0 nav-5 last level-top ui-menu-item <?php if ($url === $contactCategory->getUrl()) {echo 'active';}?>" role="presentation">
            <a id="ui-id-8" class="level-top ui-corner-all" href="<?php echo $contactCategory->getUrl();?>" tabindex="-1" role="menuitem">
                <span><?php echo $contactCategory->getName() ?></span>
            </a>
        </li>
    </ul>
</nav>
