<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_product = $block->getProduct();
    $url = $this->getUrl();
?>
<?php if ($_additional = $block->getAdditionalData()): ?>
    <div class="additional-attributes-wrapper">


            <?php foreach ($_additional as $_data): ?>

                <?php if ($_data['label'] == 'Product Brand'):?>
                    <?php $brand = $_helper->productAttribute($_product, $_data['value'], $_data['code']);
                          $brand = strtolower($brand);
                    $brandLink = str_replace(' ', '-', $brand);
                    $brandImg = str_replace(' ', '_', $brand);
                    ?>
                    <a class="brand" href="<?php echo $url . 'brand/' . $brandLink.'.html'?>">
                        <img src="<?php echo $url . 'pub/media/ves/brand/' . $brandImg . '.png'?>"
                    </a>


                <?php endif;?>
            <?php endforeach; ?>


    </div>
<?php endif;?>
